ARG version
FROM almalinux:${version:-8}
ARG course=DevOps
ARG duration=120hrs
ARG Trainer=Vijaysai
ENV Trainer=${Trainer}
RUN echo "course is ${course} and duration for course is ${course} and Trainer is ${Trainer}"
CMD [ "sleep","100" ]

